version: 0.2

phases:
  pre_build:
    commands:
      - |
        echo "▶ Stage 3 — login to destination ECR"
        aws ecr get-login-password --region $AWS_REGION | docker login -u AWS --password-stdin $ECR_REGISTRY
        echo "Using BASE_IMAGE=$BASE_IMAGE_DEFAULT"

  build:
    commands:
      - |
        echo "▶ Build overlay image from PR commit"
        echo "Tag: $CODEBUILD_RESOLVED_SOURCE_VERSION"
        docker build --build-arg BASE_IMAGE=$BASE_IMAGE_DEFAULT \
          -f Dockerfile.rebase \
          -t $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION \
          .

  post_build:
    commands:
      - |
        echo "▶ Push overlay image"
        docker push $ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
        echo "IMAGE_URI=$ECR_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION" | tee image-detail.txt

artifacts:
  files:
    - image-detail.txt

env:
  variables:
    AWS_REGION:         us-west-2
    ECR_REGISTRY:       placeholder
    ECR_URI:            placeholder
    BASE_IMAGE_DEFAULT: 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference-neuronx:2.1.2-neuronx-py310-sdk2.20.2-ubuntu20.04
