# buildspec-full.yml  (replaces separate stage-3 / stage-4 files)
version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions: { docker: 24 }
    commands:
      - set -euo pipefail
      - curl -fsSL "$KAIZEN_CLI_URL" -o kaizen && chmod +x kaizen
  pre_build:
    commands:
      - set -euo pipefail
      - aws ecr get-login-password --region "$AWS_REGION" | docker login -u AWS --password-stdin "$ECR_REGISTRY"
      - IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "Using BASE_IMAGE=$BASE_IMAGE"
  build:
    commands:
      - docker build --build-arg BASE_IMAGE="$BASE_IMAGE" -f Dockerfile.rebase -t overlay:"$IMAGE_TAG" .
  post_build:
    commands:
      - set -euo pipefail
      # ── push overlay to Kaizen (1229) ────────────────────────────────────────────
      - docker tag overlay:"$IMAGE_TAG" "$KAIZEN_ECR_URI:$IMAGE_TAG"
      - aws ecr get-login-password --region "$KAIZEN_REGION" | docker login -u AWS --password-stdin "$KAIZEN_ECR_REGISTRY"
      - docker push "$KAIZEN_ECR_URI:$IMAGE_TAG"
      # ── launch Kaizen test & stream logs; non-zero exit => build fails ──────────
      - ./kaizen start-workload \
          --image "$KAIZEN_ECR_URI:$IMAGE_TAG" \
          --instanceType "$KAIZEN_INSTANCE_TYPE" \
          --nodeCount "$KAIZEN_NODE_COUNT" \
          --command "$KAIZEN_COMMAND" \
          --wait-for-completion=true \
          --tail-logs
artifacts:
  files: []      # we just need the logs, not image details
