FROM public.ecr.aws/neuron/pytorch-inference-neuronx:2.1.2-neuronx-py310-sdk2.20.2-ubuntu20.04

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

WORKDIR /workspace
COPY . /workspace/src

RUN pip uninstall -y vllm || true

WORKDIR /workspace/src
RUN pip install --no-cache-dir -e .

CMD ["python", "examples/offline_inference/neuron.py"]
