name: Stage-3 (Build vLLM overlay image)

on:
  workflow_dispatch:          # manual run button
  pull_request:               # auto on PRs (comment out until stable if you like)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Start CodeBuild (Stage 3)
        run: |
          aws codebuild start-build \
            --project-name kaizen-poc \
            --source-version ${{ github.sha }} \
            --buildspec-override buildspec-stage3.yml \
            --environment-variables-override \
              name=AWS_REGION,value=${{ secrets.AWS_REGION }},type=PLAINTEXT \
              name=ECR_REGISTRY,value=${{ secrets.ECR_REGISTRY }},type=PLAINTEXT \
              name=ECR_URI,value=${{ secrets.ECR_URI }},type=PLAINTEXT
